#model input
model_input:
  ratings_dataset: "ratings.csv"
  items_dataset: "movies.csv"
  extra_items_dataset: "extra_movies.csv"
  rating_scale: [0.5, 1, 1.5, 2, 2.5, 3, 3.5, 4, 4.5, 5]
  recommendation_data_directory: "recdata"
  trust_data_dir: "trust"
  data_directory: "data"
  dataset_directory: "dataset"
  results_directory: "results"
  execution_dir: "exec"

# model parameters
model_parameters:
  timesteps: 1000
  number_of_runs: 7
  quantile_consumer_expectation: [0.75]
  recommendation_strategy:
    [
      "consumer-centric",
      "profit-centric",
      "consumer-biased",
      "balanced",
      "popular-uncorrelated-profit",
      "popular-correlated-profit",
    ]
  recommendation_length: 10
  error: { "mu": 0, "sd": 0.1 } #(0.1,0.5)  (0.05,0.15)
  frequency_update_expectation: 100

  update_utilities: 0

  # frequency_recompute_utilities: 100
  # Three functions could be used to compute the distance: euclidean
  trust_update_distance: "euclidean"
  feedback_likelihood: 0.10

  # social media
  social_media_on: 0
  observing_socialmedia_likelihood: 0.75 #(0.6,0.9)
  social_media_reliance: 0.5
  numposts_threshold: 2800 #(600,5000)
  social_media_weight: 0.5
  trust_weight: 0.5

  social_media_prob_noise: 0.01
  social_media_smooth_min_rate: 0.0001
  social_media_smooth_max_rate: 0.001

  # adding new items
  add_new_item: 0
  frequency_adding_items: 100
  num_items: 50

  #dropout
  drop_out_on: 1
  dropout_threshold: 0.9

  # switch strategy
  switch_strategy: 0
  period_switch: 30

  profit_threshold: 1647
  reputation_threshold: 0.6
  n: 10
